### ISSUE TITLE
File checker

### ISSUE THREAD

**Issue by HennecartLisa** [HennecartLisa/fillit02#2]
read file
check char '/n' XOR '.' XOR '#'
stucture
Tetriminos
nb or tetriminos 1 <= nb <= 26

return 0 if correct
           1 if false
           -1 if file doesn't exit

**Comment by zszeredi** [comment]
> read file - done
> check char '/n' XOR '.' XOR '#' - done
> stucture - not sure
> Tetriminos -  not sure
> nb or tetriminos 1 <= nb <= 26 - done
> 
> return 0 if correct
> 1 if false
> -1 if file doesn't exit
